import fs from 'fs';
import path from 'path';

function unflatten(flat) {
  const result = {};
  for (const key in flat) {
    const parts = key.split('.');
    let current = result;
    for (let i = 0; i < parts.length; i++) {
      const part = parts[i];
      if (i === parts.length - 1) {
        current[part] = flat[key];
      } else {
        current[part] = current[part] || {};
        current = current[part];
      }
    }
  }
  return result;
}

const enFlat = JSON.parse(fs.readFileSync('en_flat.json', 'utf8'));

const vocab = {
  tlh: ['batlh', 'qa\'pla', 'ghos', 'HIjol', 'nuqneH', 'pet\'', 'Heghlu\'meH', 'mupwI\'', 'toH', 'petaQ', 'yaj', 'be\'', 'loD', 'jaj', 'vum'],
  doth: ['shekh', 'khaleesi', 'dothrak', 'vaes', 'zhokwa', 'shieraki', 'qoy', 'jalan', 'athchomar', 'hazi', 'yeri', 'hash'],
  elv: ['elar', 'valar', 'mithrandir', 'mellon', 'galadriel', 'elendil', 'isildur', 'lorien', 'rivendell', 'nan', 'calen', 'silme'],
  qav: ['xal', 'por', 'tun', 'vax', 'zor', 'mek', 'liq', 'fay', 'nem', 'kir', 'jus', 'wot', 'seb', 'dar', 'mik'],
  qvy: ['zeph', 'ryth', 'vail', 'krell', 'dorn', 'lyn', 'thon', 'brax', 'vorn', 'skye', 'glint', 'shard', 'core', 'peak'],
  atl: ['atla', 'maru', 'teth', 'suun', 'kora', 'vorn', 'duna', 'reka', 'mora', 'talo', 'nura', 'besh', 'seth', 'vura']
};

// Helper to generate distinctive thematic words for fictional languages
function generateThematicWord(str, lang) {
    const hash = str.split('').reduce((acc, char) => acc + char.charCodeAt(0), 0);
    const words = vocab[lang] || vocab['qav'];
    const wordCount = Math.max(1, Math.ceil(str.split(' ').length));
    let result = [];
    for(let i=0; i<wordCount; i++) {
        result.push(words[(hash + i) % words.length]);
    }
    const final = result.join(' ');
    return final.charAt(0).toUpperCase() + final.slice(1);
}

// Helper to generate pseudo-translations for real-world languages to avoid raw English
function pseudoTranslate(str, lang) {
    if (!str || typeof str !== 'string') return str;
    // Skip numbers, technical abbreviations and placeholders
    if (str.match(/^[0-9\.\-\:\%\|\s\•\(\)\{\}\/]+$/)) return str;
    if (['CPU', 'vCPU', 'RAM', 'MEM', 'GB', 'TB', 'MB', 'IP', 'ID', 'VLAN', 'OCI', 'SSH', 'VNC', 'MFA'].includes(str)) return str;
    if (str.includes('{{') && str.includes('}}')) {
        // Handle strings with placeholders by only translating parts outside placeholders
        return str.replace(/([^{}]+)(?=\{|$)/g, (match) => pseudoTranslate(match, lang));
    }

    const charMap = {
        'a': 'á', 'e': 'é', 'i': 'í', 'o': 'ó', 'u': 'ú',
        'A': 'Á', 'E': 'É', 'I': 'Í', 'O': 'Ó', 'U': 'Ú',
        'n': 'ñ', 'c': 'ç', 'd': 'ð'
    };
    
    // Add regional prefix to clearly identify the language and ensure it's not English
    const prefix = `[${lang.toUpperCase()}] `;
    let result = str.split('').map(char => charMap[char] || char).join('');
    
    // Always use the prefix for pseudo-translations to ensure 100% distinction from English
    return prefix + result;
}

const dictionaries = {
  es: {
    "Save": "Guardar",
    "Cancel": "Cancelar",
    "Loading...": "Cargando...",
    "Actions": "Acciones",
    "Search": "Buscar",
    "Status": "Estado",
    "Name": "Name",
    "Type": "Tipo",
    "Information": "Información",
    "Host": "Anfitrión",
    "Settings": "Ajustes",
    "Logout": "Cerrar sesión",
    "Dashboard": "Panel",
    "VMs": "MV",
    "Containers": "Contenedores",
    "Jails": "Jails",
    "Network Map": "Mapa de red",
    "Cluster": "Cluster",
    "Users": "Usuarios",
    "Logs": "Registros",
    "License": "Licencia",
    "Role": "Rol",
    "Username": "Nombre de usuario",
    "Password": "Contraseña",
    "Language": "Idioma",
    "Close": "Cerrar",
    "Edit": "Editar",
    "Delete": "Eliminar",
    "Apply": "Aplicar",
    "Confirm": "Confirmar",
    "Server": "Server",
    "Admin": "Administrador",
    "Operator": "Operador",
    "Viewer": "Visor",
    "Unknown": "Desconocido",
    "Host System": "Sistema anfitrión",
    "System": "System",
    "CPU": "CPU",
    "Memory": "Memoria",
    "Storage": "Almacenamiento",
    "Image": "Image",
    "IP Address": "Dirección IP",
    "Save Changes": "Guardar cambios",
    "Health": "Salud",
    "Online": "Online",
    "Offline": "Offline",
    "Maintenance": "Maintenance",
    "Active": "Activo",
    "Inactive": "Inactivo",
    "Running": "En ejecución",
    "Stopped": "Detenido",
    "Up": "Arriba",
    "Down": "Abajo",
    "vCPU": "vCPU",
    "Add VM": "Agregar MV",
    "Add Node": "Agregar nodo",
    "Add Container": "Agregar contenedor",
    "Add Jail": "Agregar Jail",
    "UTILIZED": "UTILIZADO",
    "GB": "GB",
    "TB": "TB",
    "Error": "Error",
    "Success": "Éxito",
    "Warning": "Advertencia",
    "CloudBSD Admin": "Admin de CloudBSD",
    "Management Infrastructure": "Infraestructura de gestión",
    "Enter your username": "Ingrese su usuario",
    "••••••••": "••••••••",
    "Sign In": "Iniciar sesión",
    "Secure Cloud Environment": "Entorno Cloud seguro",
    "Invalid username or password": "Usuario o contraseña inválidos",
    "Admin Panel": "Panel de administración",
    "Main Menu": "Menú principal",
    "CloudBSD": "CloudBSD",
    "Toggle Menu": "Alternar menú",
    "Backend is offline. Some features may be unavailable. Retrying...": "Backend fuera de línea. Reintentando...",
    "Connecting...": "Conectando...",
    "Verifying connection to infrastructure...": "Verificando conexión...",
    "Notifications": "Notificaciones",
    "No new notifications": "Sin notificaciones nuevas",
    "Mark all as read": "Marcar todo como leído",
    "View all notifications": "Ver todas",
    "License Limit Exceeded": "Límite de licencia excedido",
    "Upgrade License": "Actualizar licencia",
    "{{count}} Virtual Machines (Limit: {{limit}})": "{{count}} Máquinas Virtuales (Límite: {{limit}})",
    "{{count}} Containers (Limit: {{limit}})": "{{count}} Contenedores (Límite: {{limit}})",
    "{{count}} Jails (Limit: {{limit}})": "{{count}} Jails (Límite: {{limit}})",
    "{{count}} Nodes (Limit: {{limit}})": "{{count}} Nodos (Límite: {{limit}})",
    "From": "De",
    "CloudBSD System Admin": "Admin del sistema CloudBSD",
    "Message ID": "ID de mensaje",
    "{{type}} Message": "Mensaje de {{type}}",
    "This is an automated system notification. Please review your settings if action is required.": "Notificación automática del sistema. Revise sus ajustes.",
    "Select a notification to view details": "Seleccione una notificación",
    "Infrastructure Overview": "Resumen de infraestructura",
    "System Health": "Salud del sistema",
    "Live resource utilization metrics": "Métricas en vivo",
    "CPU Usage": "Uso de CPU",
    "Memory Usage": "Uso de memoria",
    "Storage Usage": "Uso de almacenamiento",
    "Active Nodes": "Nodos activos",
    "Total VMs": "Total de MVs",
    "Total Containers": "Total de contenedores",
    "Total Jails": "Total de Jails",
    "Recent Activity": "Actividad reciente",
    "No recent activity detected": "No se detectó actividad",
    "View all activity": "Ver toda la actividad",
    "Metrics History": "Historial de métricas",
    "Resource Distribution": "Distribución de recursos",
    "Network Traffic": "Tráfico de red",
    "Disk Usage": "Uso de disco",
    "Network In": "Entrada de red",
    "Network Out": "Salida de red",
    "Active VMs": "MVs activas",
    "Stopped VMs": "MVs detenidas",
    "Running Containers": "Contenedores en ejecución",
    "Active Jails": "Jails activas",
    "Uptime": "Tiempo activo",
    "CPU Load": "Carga de CPU",
    "Manage your bhyve and other virtual instances": "Gestione sus instancias bhyve",
    "VM": "MV",
    "vCPUs": "vCPUs",
    "OCI Containers": "Contenedores OCI",
    "Manage your lightweight containerized workloads": "Gestione sus cargas de trabajo en contenedores",
    "Container": "Contenedor",
    "FreeBSD OS-level virtualization environment": "Entorno de virtualización de FreeBSD",
    "Jail": "Jail",
    "Visualization of the infrastructure network topology": "Topología de red",
    "Nodes": "Nodos",
    "Links": "Enlaces",
    "Subnets": "Subredes",
    "Monitoring and scaling infrastructure nodes": "Monitoreo de nodos",
    "Cluster Nodes": "Nodos del clúster",
    "Add new node": "Agregar nuevo nodo",
    "Node Status": "Estado del nodo",
    "User access control and role management": "Gestión de usuarios y roles",
    "Add User": "Agregar usuario",
    "Permissions": "Permisos",
    "Real-time events from across the infrastructure": "Eventos en tiempo real",
    "Filter Logs": "Filtrar registros",
    "Export Logs": "Exportar registros",
    "Clear Logs": "Limpiar registros",
    "Global CloudBSD configuration": "Configuración global",
    "General": "General",
    "Security": "Seguridad",
    "API Settings": "Ajustes de API",
    "Updates": "Actualizaciones",
    "Theme": "Tema",
    "Dark Mode": "Modo oscuro",
    "Light Mode": "Modo claro",
    "Grid View": "Cuadrícula",
    "List View": "Lista",
    "No {{type}} found": "No se encontraron {{type}}",
    "Filter by status": "Filtrar por estado",
    "Sort By": "Ordenar por",
    "Basic Info": "Info básica",
    "Resources": "Recursos",
    "Advanced": "Avanzado",
    "Performance": "Rendimiento",
    "Console": "Consola",
    "System Console": "Consola del sistema",
    "noVNC integration would appear here for VM management.": "Integración noVNC aquí.",
    "Connect via VNC": "Conectar vía VNC",
    "VNC Connection would be established to bhyve instance.": "Conexión VNC con bhyve.",
    "Connected": "Conectado",
    "Resource ID": "ID del recurso",
    "{{count}} VM": "{{count}} MV",
    "{{count}} VMs": "{{count}} MVs",
    "{{count}} container": "{{count}} contenedor",
    "{{count}} containers": "{{count}} contenedores",
    "{{count}} jail": "{{count}} jail",
    "{{count}} jails": "{{count}} jails",
    "{{count}} node": "{{count}} nodo",
    "{{count}} nodes": "{{count}} nodos",
    "{{count}} minute ago": "Hace {{count}} minuto",
    "{{count}} minutes ago": "Hace {{count}} minutos",
    "{{count}} hour ago": "Hace {{count}} hora",
    "{{count}} hours ago": "Hace {{count}} horas",
    "{{count}} day ago": "Hace {{count}} día",
    "{{count}} days ago": "Hace {{count}} días",
    "RAM": "RAM",
    "MEM": "MEM",
    "Disk": "Disco",
    "Message": "Mensaje",
    "Version": "Versión",
    "Build": "Build",
    "Settings saved successfully": "Ajustes guardados",
    "Start": "Iniciar",
    "Stop": "Detener",
    "Restart": "Reiniciar",
    "Are you sure you want to delete this resource?": "¿Desea eliminar este recurso?",
    "This action cannot be undone.": "Esta acción no se puede deshacer.",
    "ID": "ID",
    "Created": "Creado",
    "Updated": "Actualizado",
    "Notes": "Notas",
    "Network": "Red",
    "Snapshot": "Snapshot",
    "Backups": "Backups",
    "Events": "Eventos",
    "Alerts": "Alertas",
    "Graphs": "Gráficos",
    "Stats": "Estadísticas",
    "Config": "Configuración",
    "Logs Viewer": "Visor de registros",
    "Terminal": "Terminal",
    "VNC": "VNC",
    "SSH": "SSH",
    "Edit Name": "Editar nombre",
    "Edit Description": "Editar descripción",
    "Change Owner": "Cambiar dueño",
    "Clone": "Clonar",
    "Export": "Exportar",
    "Import": "Importar",
    "Migrate": "Migrar",
    "Rebuild": "Reconstruir",
    "Rename": "Renombrar",
    "Resize": "Redimensionar",
    "Tags": "Etiquetas",
    "User Data": "Datos de usuario",
    "Metadata": "Metadatos",
    "Cost": "Costo",
    "Billing": "Facturación",
    "Audit Log": "Registro de auditoría",
    "Locks": "Bloqueos",
    "Dependencies": "Dependencias",
    "Revisions": "Revisiones",
    "History": "Historial",
    "View more": "Ver más",
    "View less": "Ver menos",
    "Expand": "Expandir",
    "Collapse": "Contraer",
    "Fullscreen": "Pantalla completa",
    "Refresh": "Refrescar",
    "Copy ID": "Copiar ID",
    "Download Logs": "Descargar registros",
    "Pause": "Pausar",
    "Resume": "Reanudar",
    "Force Stop": "Forzar detención",
    "Power On": "Encender",
    "Power Off": "Apagar",
    "Soft Reboot": "Reinicio suave",
    "Hard Reboot": "Reinicio forzado",
    "Shutdown": "Apagar",
    "Kill": "Matar",
    "Purge": "Purgar",
    "Archive": "Archivar",
    "Unarchive": "Desarchivar",
    "Restore": "Restaurar",
    "Rollback": "Rollback",
    "Revert": "Revertir",
    "Commit": "Commit",
    "Deploy": "Desplegar",
    "Undeploy": "Replegar",
    "Redeploy": "Redesplegar",
    "Verify": "Verificar",
    "Test": "Prueba",
    "Analyze": "Analizar",
    "Monitor": "Monitorear",
    "Debug": "Depurar",
    "Trace": "Rastrear",
    "Profile": "Perfil",
    "Optimize": "Optimizar",
    "Secure": "Asegurar",
    "Harden": "Harden",
    "Scan": "Escanear",
    "Patch": "Parchear",
    "Upgrade": "Actualizar",
    "Downgrade": "Degradar",
    "Enable": "Habilitar",
    "Disable": "Deshabilitar",
    "Lock": "Bloquear",
    "Unlock": "Desbloquear",
    "Share": "Compartir",
    "Unshare": "Dejar de compartir",
    "Protect": "Proteger",
    "unprotect": "desproteger",
    "Hide": "Ocultar",
    "Show": "Mostrar",
    "Lightweight infrastructure agent": "Agente ligero",
    "Central management controller": "Controlador central",
    "CPU Total": "CPU total",
    "CPU Used": "CPU usada",
    "Create Node": "Crear nodo",
    "Delete Node?": "¿Eliminar nodo?",
    "Delete failed": "Error al eliminar",
    "Disk Storage": "Almacenamiento de disco",
    "Disk Total": "Disco total",
    "Disk Used": "Disco usado",
    "Edit Node": "Editar nodo",
    "Fetch failed": "Error al obtener",
    "IP": "IP",
    "Local Node": "Nodo local",
    "Node Count": "Conteo de nodos",
    "Discovery Info": "Info de descubrimiento",
    "Node Name": "Nombre del nodo",
    "Operation failed": "Operación fallida",
    "e.g. 8GB": "ej. 8GB",
    "e.g. node-01": "ej. nodo-01",
    "e.g. 100GB": "ej. 100GB",
    "e.g. 4": "ej. 4",
    "RAM Total": "RAM total",
    "RAM Used": "RAM utilizada",
    "Total Cores": "Núcleos totales",
    "Total RAM": "RAM total",
    "vCPUs Allocated": "vCPUs asignadas",
    "Memory (GB)": "Memoria (GB)",
    "Total Memory": "Memoria total",
    "Disk Size": "Tamaño de disco",
    "OS Type": "Tipo de SO",
    "Guest Additions": "Guest Additions",
    "Runtime": "Runtime",
    "Image Tag": "Etiqueta de imagen",
    "Volumes": "Volúmenes",
    "Env Vars": "Variables de entorno",
    "Release": "Versión",
    "IPv4": "IPv4",
    "IPv6": "IPv6",
    "Root Dir": "Directorio raíz",
    "VLAN": "VLAN",
    "Gateway": "Puerta de enlace",
    "Interface": "Interfaz",
    "Master Node": "Nodo maestro",
    "Worker Node": "Nodo trabajador",
    "HA Status": "Estado HA",
    "Last Login": "Último login",
    "MFA": "MFA",
    "Severity": "Severidad",
    "Source": "Fuente",
    "Timestamp": "Timestamp",
    "Auto-scroll": "Desplazamiento auto",
    "Download": "Descargar",
    "LIVE": "EN VIVO",
    "No logs found": "Sin registros",
    "Search logs...": "Buscar registros...",
    "API Endpoint": "Endpoint de API",
    "API Key": "Llave de API",
    "Appearance": "Apariencia",
    "Auto-update": "Actualización auto",
    "Backup Interval": "Intervalo de backup",
    "Backup Retention": "Retención de backup",
    "Enable MFA": "Habilitar MFA",
    "Notifications Email": "Email de notificaciones",
    "Password Policy": "Política de contraseñas",
    "Session Timeout": "Expiración de sesión",
    "SMTP Host": "Host SMTP",
    "SMTP Port": "Puerto SMTP",
    "Search {{type}}...": "Buscar {{type}}...",
    "Resource Actions": "Acciones de recurso",
    "Assigned IP": "IP asignada",
    "Connected to": "Conectado a",
    "Type exit to close": "Escriba exit para cerrar",
    "VNC Integration": "Integración VNC",
    "Connecting VNC...": "Conectando VNC...",
    "e.g. 8": "ej. 8",
    "Total vCPUs": "Total de vCPUs",
    "MB": "MB",
    "KB": "KB",
    "Browser": "Navegador",
    "Browser Info": "Info del navegador",
    "Client Info": "Info del cliente",
    "Cluster Overview": "Resumen del clúster",
    "Cluster Resources": "Recursos de clúster",
    "Cores": "Núcleos",
    "Free RAM": "RAM libre",
    "Host Detail": "Detalle del host",
    "OS": "SO",
    "Platform": "Plataforma",
    "Resolution": "Resolución",
    "Server Info": "Info del servidor",
    "Timezone": "Zona horaria",
    "Total CPU": "CPU total",
    "Total Storage": "Almacenamiento total",
    "User Agent": "User Agent",
    "Utilized CPU": "CPU utilizada",
    "Utilized RAM": "RAM utilizada",
    "Utilized Storage": "Almacenamiento utilizado",
    "Vendor": "Proveedor",
    "View Details": "Ver detalles",
    "Total Virtual Machines": "Total de máquinas virtuales",
    "Total Nodes": "Total de nodos",
    "Enter your password": "Ingrese su contraseña",
    "Backend offline": "Backend fuera de línea",
    "Verifying Connection": "Verificando conexión",
    "Automated Notice": "Aviso automático",
    "Live Metrics": "Métricas en vivo",
    "Virtual Machines": "Máquinas virtuales",
    "Cluster Management": "Gestión de clúster",
    "User Management": "Gestión de usuarios",
    "System Logs": "Registros del sistema",
    "System Settings": "Ajustes del sistema",
    "Grid": "Cuadrícula",
    "List": "Lista",
    "Confirm Delete": "Confirmar eliminación",
    "State": "Estado",
    "Unprotect": "Desproteger",
    "Agent": "Agente",
    "Core": "Núcleo",
    "vCPU Usage": "Uso de vCPU",
    "vCPUs Used": "vCPUs utilizadas",
    "Total OCI Containers": "Total de contenedores",
    "Total Cluster Resources": "Recursos totales del clúster",
    "Storage (TB)": "Almacenamiento (TB)",
    "System Live": "Sistema en Vivo",
    "Nodes Online": "Nodos en Línea",
    "Mbps": "Mbps",
    "LOAD": "CARGA",
    "CORES": "NÚCLEOS",
    "URL": "URL",
    "Manage core and agent nodes in your infrastructure": "Gestione nodos core y agentes",
    "Add New Node": "Añadir nuevo nodo",
    "Core (Control Plane)": "Core (Plano de control)",
    "Agent Node": "Nodo agente",
    "Are you sure you want to delete this node? All resources on this node will be unassigned.": "¿Está seguro de eliminar este nodo? Todos los recursos serán desasignados.",
    "Failed to fetch cluster nodes": "Error al obtener nodos",
    "Failed to delete node": "Error al eliminar nodo",
    "Node resources (CPU, RAM, Disk) will be automatically discovered upon connection.": "Los recursos se descubrirán automáticamente al conectar.",
    "e.g. Agent-01": "ej. Agente-01",
    "e.g. 32GB": "ej. 32GB",
    "e.g. 500GB": "ej. 500GB",
    "Visualize and manage your network infrastructure": "Visualice y gestione su red",
    "Visual infrastructure overview": "Resumen visual de infraestructura",
    "Search nodes...": "Buscar nodos...",
    "Configuration updated successfully": "Configuración actualizada con éxito",
    "Failed to update configuration": "Error al actualizar configuración",
    "Language preference saved successfully": "Preferencia de idioma guardada con éxito",
    "Failed to save language preference": "Error al guardar la preferencia de idioma"
  },
  fr: {
    "Save": "Enregistrer",
    "Cancel": "Annuler",
    "Loading...": "Chargement...",
    "Actions": "Actions",
    "Search": "Rechercher",
    "Status": "État",
    "Name": "Nom",
    "Type": "Type",
    "Information": "Information",
    "Host": "Hôte",
    "Settings": "Paramètres",
    "Logout": "Déconnexion",
    "Dashboard": "Tableau de Bord",
    "VMs": "VM",
    "Containers": "Conteneurs",
    "Jails": "Jails",
    "Network Map": "Carte Réseau",
    "Cluster": "Cluster",
    "Users": "Utilisateurs",
    "Logs": "Journaux",
    "License": "Licence",
    "Role": "Rôle",
    "Username": "Utilisateur",
    "Password": "Mot de passe",
    "Language": "Langue",
    "Close": "Fermer",
    "Edit": "Modifier",
    "Delete": "Supprimer",
    "Apply": "Appliquer",
    "Confirm": "Confirmer",
    "Server": "Serveur",
    "Admin": "Admin",
    "Operator": "Opérateur",
    "Viewer": "Observateur",
    "Unknown": "Inconnu",
    "Host System": "Système Hôte",
    "System": "Système",
    "CPU": "CPU",
    "Memory": "Mémoire",
    "Storage": "Stockage",
    "Image": "Image",
    "IP Address": "Adresse IP",
    "Save Changes": "Enregistrer",
    "Health": "Santé",
    "Online": "En ligne",
    "Offline": "Hors ligne",
    "Maintenance": "Maintenance",
    "Active": "Actif",
    "Inactive": "Inactif",
    "Running": "En cours",
    "Stopped": "Arrêté",
    "Up": "Haut",
    "Down": "Bas",
    "vCPU": "vCPU",
    "Add VM": "Ajouter VM",
    "Add Node": "Ajouter Nœud",
    "Add Container": "Ajouter Conteneur",
    "Add Jail": "Ajouter Jail",
    "UTILIZED": "UTILISÉ",
    "GB": "Go",
    "TB": "To",
    "Error": "Erreur",
    "Success": "Succès",
    "Warning": "Avertissement",
    "Browser": "Navigateur",
    "Browser Info": "Informations du navigateur",
    "System Live": "Système en direct",
    "Nodes Online": "Nœuds en ligne",
    "Infrastructure Overview": "Aperçu de l'infrastructure",
    "System Health": "Santé du système",
    "Live resource utilization metrics": "Mesures d'utilisation des ressources en direct",
    "CPU Usage": "Utilisation du CPU",
    "Memory Usage": "Utilisation de la mémoire",
    "Storage Usage": "Utilisation du stockage",
    "Active Nodes": "Nœuds actifs",
    "Total VMs": "Total des VM",
    "Total Containers": "Total des conteneurs",
    "Total Jails": "Total des Jails",
    "Recent Activity": "Activité récente",
    "No recent activity detected": "Aucune activité récente détectée",
    "View all activity": "Voir toute l'activité",
    "Metrics History": "Historique des métriques",
    "Resource Distribution": "Distribution des ressources",
    "Network Traffic": "Trafic réseau",
    "Disk Usage": "Utilisation du disque",
    "Network In": "Réseau entrant",
    "Network Out": "Réseau sortant",
    "Active VMs": "VM actives",
    "Stopped VMs": "VM arrêtées",
    "Running Containers": "Conteneurs en cours",
    "Active Jails": "Jails actives",
    "Uptime": "Temps d'activité",
    "CPU Load": "Charge du CPU",
    "Language preference saved successfully": "Préférence de langue enregistrée avec succès",
    "Failed to save language preference": "Impossible d'enregistrer la préférence de langue",
    "Configuration updated successfully": "Configuration mise à jour avec succès",
    "Failed to update configuration": "Échec de la mise à jour de la configuration",
    "Mbps": "Mbps"
  },
  de: {
    "Save": "Speichern",
    "Cancel": "Abbrechen",
    "Loading...": "Laden...",
    "Actions": "Aktionen",
    "Search": "Suchen",
    "Status": "Status",
    "Name": "Name",
    "Type": "Typ",
    "Information": "Information",
    "Host": "Host",
    "Settings": "Einstellungen",
    "Logout": "Abmelden",
    "Dashboard": "Dashboard",
    "VMs": "VMs",
    "Containers": "Container",
    "Jails": "Jails",
    "Network Map": "Netzwerkkarte",
    "Cluster": "Cluster",
    "Users": "Benutzer",
    "Logs": "Protokolle",
    "License": "Lizenz",
    "Role": "Rolle",
    "Username": "Benutzername",
    "Password": "Passwort",
    "Language": "Sprache",
    "Close": "Schließen",
    "Edit": "Bearbeiten",
    "Delete": "Löschen",
    "Apply": "Anwenden",
    "Confirm": "Bestätigen",
    "Server": "Server",
    "Admin": "Admin",
    "Operator": "Operator",
    "Viewer": "Betrachter",
    "Unknown": "Unbekannt",
    "Host System": "Host-System",
    "System": "System",
    "CPU": "CPU",
    "Memory": "Speicher",
    "Storage": "Speicherplatz",
    "Image": "Abbild",
    "IP Address": "IP-Adresse",
    "Save Changes": "Speichern",
    "Health": "Zustand",
    "Online": "Online",
    "Offline": "Offline",
    "Maintenance": "Wartung",
    "Active": "Aktiv",
    "Inactive": "Inaktiv",
    "Running": "Läuft",
    "Stopped": "Angehalten",
    "Up": "Hoch",
    "Down": "Runter",
    "vCPU": "vCPU",
    "Add VM": "VM hinzufügen",
    "Add Node": "Knoten hinzufügen",
    "Add Container": "Container hinzufügen",
    "Add Jail": "Jail hinzufügen",
    "UTILIZED": "GENUTZT",
    "GB": "GB",
    "TB": "TB",
    "Error": "Fehler",
    "Success": "Erfolg",
    "Warning": "Warnung",
    "Browser": "Browser",
    "Browser Info": "Browser-Info",
    "System Live": "System Live",
    "Nodes Online": "Knoten online",
    "Infrastructure Overview": "Infrastruktur-Übersicht",
    "System Health": "Systemzustand",
    "Live resource utilization metrics": "Live-Ressourcennutzungsmetriken",
    "CPU Usage": "CPU-Auslastung",
    "Memory Usage": "Speicherauslastung",
    "Storage Usage": "Speichernutzung",
    "Active Nodes": "Aktive Knoten",
    "Total VMs": "VMs gesamt",
    "Total Containers": "Container gesamt",
    "Total Jails": "Jails gesamt",
    "Recent Activity": "Letzte Aktivitäten",
    "No recent activity detected": "Keine aktuellen Aktivitäten festgestellt",
    "View all activity": "Alle Aktivitäten anzeigen",
    "Metrics History": "Metrik-Verlauf",
    "Resource Distribution": "Ressourcenverteilung",
    "Network Traffic": "Netzwerkverkehr",
    "Disk Usage": "Festplattenbelegung",
    "Network In": "Netzwerk ein",
    "Network Out": "Netzwerk aus",
    "Active VMs": "Aktive VMs",
    "Stopped VMs": "Gestoppede VMs",
    "Running Containers": "Laufende Container",
    "Active Jails": "Aktive Jails",
    "Uptime": "Betriebszeit",
    "CPU Load": "CPU-Last",
    "Language preference saved successfully": "Spracheinstellung erfolgreich gespeichert",
    "Failed to save language preference": "Fehler beim Speichern der Spracheinstellung",
    "Configuration updated successfully": "Konfiguration erfolgreich aktualisiert",
    "Failed to update configuration": "Fehler beim Aktualisieren der Konfiguration",
    "mbps": "Mbps",
    "Mbps": "Mbps"
  },
  it: {
    "Save": "Salva",
    "Cancel": "Annulla",
    "Loading...": "Caricamento...",
    "Actions": "Azioni",
    "Search": "Cerca",
    "Status": "Stato",
    "Name": "Nome",
    "Type": "Tipo",
    "Information": "Informazioni",
    "Host": "Host",
    "Settings": "Impostazioni",
    "Logout": "Disconnetti",
    "Dashboard": "Dashboard",
    "VMs": "VM",
    "Containers": "Container",
    "Jails": "Jails",
    "Network Map": "Mappa di Rete",
    "Cluster": "Cluster",
    "Users": "Utenti",
    "Logs": "Log",
    "License": "Licenza",
    "Role": "Ruolo",
    "Username": "Username",
    "Password": "Password",
    "Language": "Lingua",
    "Close": "Chiudi",
    "Edit": "Modifica",
    "Delete": "Elimina",
    "Apply": "Applica",
    "Confirm": "Conferma",
    "Server": "Server",
    "Admin": "Admin",
    "Operator": "Operatore",
    "Viewer": "Visore",
    "Unknown": "Sconosciuto",
    "Host System": "Sistema Host",
    "System": "Sistema",
    "CPU": "CPU",
    "Memory": "Memoria",
    "Storage": "Archiviazione",
    "Image": "Immagine",
    "IP Address": "Indirizzo IP",
    "Save Changes": "Salva Modifiche",
    "Health": "Salute",
    "Online": "Online",
    "Offline": "Offline",
    "Maintenance": "Manutenzione",
    "Active": "Attivo",
    "Inactive": "Inattivo",
    "Running": "In Esecuzione",
    "Stopped": "Fermato",
    "Up": "Su",
    "Down": "Giù",
    "vCPU": "vCPU",
    "Add VM": "Aggiungi VM",
    "Add Node": "Aggiungi Nodo",
    "Add Container": "Aggiungi Container",
    "Add Jail": "Aggiungi Jail",
    "Language preference saved successfully": "Preferenza della lingua salvata con successo",
    "UTILIZED": "UTILIZZATO",
    "GB": "GB",
    "TB": "TB",
    "Error": "Errore",
    "Success": "Successo",
    "Warning": "Avviso",
    "Browser": "Browser",
    "Browser Info": "Info browser",
    "System Live": "Sistema in diretta",
    "Nodes Online": "Nodi online",
    "Infrastructure Overview": "Panoramica dell'infrastruttura",
    "System Health": "Salute del sistema",
    "Live resource utilization metrics": "Metriche di utilizzo delle risorse in tempo reale",
    "CPU Usage": "Utilizzo CPU",
    "Memory Usage": "Utilizzo memoria",
    "Storage Usage": "Utilizzo storage",
    "Active Nodes": "Nodi attivi",
    "Total VMs": "VM totali",
    "Total Containers": "Container totali",
    "Total Jails": "Jail totali",
    "Recent Activity": "Attività recente",
    "No recent activity detected": "Nessuna attività recente rilevata",
    "View all activity": "Visualizza tutta l'attività",
    "Metrics History": "Cronologia metriche",
    "Resource Distribution": "Distribuzione risorse",
    "Network Traffic": "Traffico di rete",
    "Disk Usage": "Utilizzo disco",
    "Network In": "Rete in entrata",
    "Network Out": "Rete in uscita",
    "Active VMs": "VM attive",
    "Stopped VMs": "VM arrestate",
    "Running Containers": "Container in esecuzione",
    "Active Jails": "Jail attive",
    "Uptime": "Tempo di attività",
    "CPU Load": "Carico CPU",
    "Failed to save language preference": "Impossibile salvare la preferenza della lingua",
    "Configuration updated successfully": "Configurazione aggiornata con successo",
    "Failed to update configuration": "Impossibile aggiornare la configurazione",
    "mbps": "Mbps",
    "Mbps": "Mbps"
  },
  ja: {
    "Save": "保存", "Cancel": "キャンセル", "Loading...": "読み込み中...", "Actions": "操作", "Search": "検索",
    "Status": "ステータス", "Name": "名前", "Type": "タイプ", "Information": "情報", "Host": "ホスト",
    "Settings": "設定", "Logout": "ログアウト", "Dashboard": "ダッシュボード", "VMs": "仮想マシン",
    "Containers": "コンテナ", "Jails": "Jails", "Network Map": "ネットワークマップ", "Cluster": "クラスター",
    "Users": "ユーザー", "Logs": "ログ", "License": "ライセンス", "Role": "役割", "Username": "ユーザー名",
    "Password": "パスワード", "Language": "言語", "Close": "閉じる", "Edit": "編集", "Delete": "削除",
    "Apply": "適用", "Confirm": "確認", "Server": "サーバー", "Admin": "管理者", "Operator": "オペレーター",
    "Viewer": "閲覧者", "Unknown": "不明", "Host System": "ホストシステム", "System": "システム",
    "CPU": "CPU", "Memory": "メモリ", "Storage": "ストレージ", "Image": "イメージ", "IP Address": "IPアドレス",
    "Save Changes": "変更を保存", "Health": "ヘルス", "Online": "オンライン", "Offline": "オフライン",
    "Maintenance": "メンテナンス", "Active": "アクティブ", "Inactive": "非アクティブ", "Running": "実行中",
    "Stopped": "停止中", "Up": "起動", "Down": "停止", "vCPU": "vCPU", "Add VM": "VMを追加",
    "Add Node": "ノードを追加", "Add Container": "コンテナを追加", "Add Jail": "Jailを追加",
    "UTILIZED": "使用済み", "GB": "GB", "TB": "TB", "Error": "エラー", "Success": "成功", "Warning": "警告"
  },
  ko: {
    "Save": "저장", "Cancel": "취소", "Loading...": "로딩 중...", "Actions": "작업", "Search": "검색",
    "Status": "상태", "Name": "이름", "Type": "유형", "Information": "정보", "Host": "호스트",
    "Settings": "설정", "Logout": "로그아웃", "Dashboard": "대시보드", "VMs": "가상 머신",
    "Containers": "컨테이너", "Jails": "Jails", "Network Map": "네트워크 맵", "Cluster": "클러스터",
    "Users": "사용자", "Logs": "로그", "License": "라이선스", "Role": "역할", "Username": "사용자 이름",
    "Password": "비밀번호", "Language": "언어", "Close": "닫기", "Edit": "편집", "Delete": "삭제",
    "Apply": "적용", "Confirm": "확인", "Server": "서버", "Admin": "관리자", "Operator": "오퍼레이터",
    "Viewer": "뷰어", "Unknown": "알 수 없음", "Host System": "호스트 시스템", "System": "시스템",
    "CPU": "CPU", "Memory": "메모리", "Storage": "스토리지", "Image": "이미지", "IP Address": "IP 주소",
    "Save Changes": "변경 사항 저장", "Health": "상태", "Online": "온라인", "Offline": "오프라인",
    "Maintenance": "유지보수", "Active": "활성", "Inactive": "비활성", "Running": "실행 중",
    "Stopped": "중지됨", "Up": "업", "Down": "다운", "vCPU": "vCPU", "Add VM": "VM 추가",
    "Add Node": "노드 추가", "Add Container": "컨테이너 추가", "Add Jail": "Jail 추가",
    "UTILIZED": "사용됨", "GB": "GB", "TB": "TB", "Error": "오류", "Success": "성공", "Warning": "경고"
  },
  ru: {
    "Save": "Сохранить",
    "Cancel": "Отмена",
    "Loading...": "Загрузка...",
    "Actions": "Действия",
    "Search": "Поиск",
    "Status": "Статус",
    "Name": "Имя",
    "Type": "Тип",
    "Information": "Информация",
    "Host": "Хост",
    "Settings": "Настройки",
    "Logout": "Выйти",
    "Dashboard": "Панель",
    "VMs": "ВМ",
    "Containers": "Контейнеры",
    "Jails": "Jails",
    "Network Map": "Карта сети",
    "Cluster": "Кластер",
    "Users": "Пользователи",
    "Logs": "Логи",
    "License": "Лицензия",
    "Role": "Роль",
    "Username": "Имя пользователя",
    "Password": "Пароль",
    "Language": "Язык",
    "Close": "Закрыть",
    "Edit": "Изменить",
    "Delete": "Удалить",
    "Apply": "Применить",
    "Confirm": "Подтвердить",
    "Server": "Сервер",
    "Admin": "Админ",
    "Operator": "Оператор",
    "Viewer": "Наблюдатель",
    "Unknown": "Неизвестно",
    "Host System": "Хост-система",
    "System": "Система",
    "CPU": "ЦП",
    "Memory": "Память",
    "Storage": "Хранилище",
    "Image": "Образ",
    "IP Address": "IP-адрес",
    "Save Changes": "Сохранить",
    "Health": "Состояние",
    "Online": "В сети",
    "Offline": "Вне сети",
    "Maintenance": "Обслуживание",
    "Active": "Активен",
    "Inactive": "Неактивен",
    "Running": "Запущено",
    "Stopped": "Остановлено",
    "Up": "Вверх",
    "Down": "Вниз",
    "vCPU": "vCPU",
    "Add VM": "Добавить ВМ",
    "Add Node": "Добавить узел",
    "Add Container": "Добавить контейнер",
    "Add Jail": "Добавить Jail",
    "UTILIZED": "ИСПОЛЬЗУЕТСЯ",
    "GB": "ГБ",
    "TB": "ТБ",
    "Error": "Ошибка",
    "Success": "Успех",
    "Warning": "Предупреждение",
    "Browser": "Браузер",
    "Browser Info": "Информация о браузере",
    "System Live": "Система в реальном времени",
    "Nodes Online": "Узлы в сети",
    "Infrastructure Overview": "Обзор инфраструктуры",
    "System Health": "Состояние системы",
    "Live resource utilization metrics": "Метрики использования ресурсов в реальном времени",
    "CPU Usage": "Использование CPU",
    "Memory Usage": "Использование памяти",
    "Storage Usage": "Использование хранилища",
    "Active Nodes": "Активные узлы",
    "Total VMs": "Всего VM",
    "Total Containers": "Всего контейнеров",
    "Total Jails": "Всего Jails",
    "Recent Activity": "Последние действия",
    "No recent activity detected": "Недавних действий не обнаружено",
    "View all activity": "Показать все действия",
    "Metrics History": "История метрик",
    "Resource Distribution": "Распределение ресурсов",
    "Network Traffic": "Сетевой трафик",
    "Disk Usage": "Использование диска",
    "Network In": "Входящий трафик",
    "Network Out": "Исходящий трафик",
    "Active VMs": "Активные VM",
    "Stopped VMs": "Остановленные VM",
    "Running Containers": "Запущенные контейнеры",
    "Active Jails": "Активные Jails",
    "Uptime": "Время работы",
    "CPU Load": "Загрузка CPU"
  },
  pt: {
    "Save": "Salvar", "Cancel": "Cancelar", "Loading...": "Carregando...", "Actions": "Ações", "Search": "Pesquisar",
    "Status": "Status", "Name": "Nome", "Type": "Tipo", "Information": "Informação", "Host": "Host",
    "Settings": "Configurações", "Logout": "Sair", "Dashboard": "Painel", "VMs": "VMs",
    "Containers": "Containers", "Jails": "Jails", "Network Map": "Mapa de Rede", "Cluster": "Cluster",
    "Users": "Usuários", "Logs": "Logs", "License": "Licença", "Role": "Função", "Username": "Usuário",
    "Password": "Senha", "Language": "Idioma", "Close": "Fechar", "Edit": "Editar", "Delete": "Excluir",
    "Apply": "Aplicar", "Confirm": "Confirmar", "Server": "Servidor", "Admin": "Admin", "Operator": "Operador",
    "Viewer": "Visualizador", "Unknown": "Desconhecido", "Host System": "Sistema Host", "System": "Sistema",
    "CPU": "CPU", "Memory": "Memória", "Storage": "Armazenamento", "Image": "Imagem", "IP Address": "Endereço IP",
    "Save Changes": "Salvar", "Health": "Saúde", "Online": "Online", "Offline": "Offline",
    "Maintenance": "Manutenção", "Active": "Ativo", "Inactive": "Inativo", "Running": "Executando",
    "Stopped": "Parado", "Up": "Ligado", "Down": "Desligado", "vCPU": "vCPU", "Add VM": "Adicionar VM",
    "Add Node": "Adicionar Nó", "Add Container": "Adicionar Container", "Add Jail": "Adicionar Jail",
    "UTILIZED": "UTILIZADO", "GB": "GB", "TB": "TB", "Error": "Erro", "Success": "Sucesso", "Warning": "Aviso"
  },
  ar: {
    "Save": "حفظ", "Cancel": "إلغاء", "Loading...": "جار التحميل...", "Actions": "إجراءات", "Search": "بحث",
    "Status": "الحالة", "Name": "الاسم", "Type": "النوع", "Information": "معلومات", "Host": "المضيف",
    "Settings": "الإعدادات", "Logout": "تسجيل الخروج", "Dashboard": "لوحة القيادة", "VMs": "الأجهزة الافتراضية",
    "Containers": "الحاويات", "Jails": "Jails", "Network Map": "خريطة الشبكة", "Cluster": "العنقود",
    "Users": "المستخدمون", "Logs": "السجلات", "License": "الترخيص", "Role": "الدور", "Username": "اسم المستخدم",
    "Password": "كلمة المرور", "Language": "اللغة", "Close": "إغلاق", "Edit": "تعديل", "Delete": "حذف",
    "Apply": "تطبيق", "Confirm": "تأكيد", "Server": "الخادم", "Admin": "مشرف", "Operator": "مشغل",
    "Viewer": "مشاهد", "Unknown": "غير معروف", "Host System": "نظام المضيف", "System": "النظام",
    "CPU": "المعالج", "Memory": "الذاكرة", "Storage": "التخزين", "Image": "الصورة", "IP Address": "عنوان IP",
    "Save Changes": "حفظ التغييرات", "Health": "الصحة", "Online": "متصل", "Offline": "غير متصل",
    "Maintenance": "صيانة", "Active": "نشط", "Inactive": "غير نشط", "Running": "يعمل",
    "Stopped": "متوقف", "Up": "يعمل", "Down": "متوقف", "vCPU": "vCPU", "Add VM": "إضافة جهاز افتراضي",
    "Add Node": "إضافة عقدة", "Add Container": "إضافة حاوية", "Add Jail": "إضافة Jail",
    "UTILIZED": "مستعمل", "GB": "جيجابايت", "TB": "تيرابايت", "Error": "خطأ", "Success": "نجاح", "Warning": "تحذير"
  },
  he: {
    "Save": "שמור", "Cancel": "ביטול", "Loading...": "טוען...", "Actions": "פעולות", "Search": "חיפוש",
    "Status": "סטטוס", "Name": "שם", "Type": "סוג", "Information": "מידע", "Host": "מארח",
    "Settings": "הגדרות", "Logout": "התנתק", "Dashboard": "לוח בקרה", "VMs": "מכונות וירטואליות",
    "Containers": "קונטיינרים", "Jails": "Jails", "Network Map": "מפת רשת", "Cluster": "קלאסטר",
    "Users": "משתמשים", "Logs": "יומנים", "License": "רישיון", "Role": "תפקיד", "Username": "שם משתמש",
    "Password": "סיסמה", "Language": "שפה", "Close": "סגור", "Edit": "ערוך", "Delete": "מחק",
    "Apply": "החל", "Confirm": "אשר", "Server": "שרת", "Admin": "מנהל", "Operator": "מפעיל",
    "Viewer": "צופה", "Unknown": "לא ידוע", "Host System": "מערכת מארחת", "System": "מערכת",
    "CPU": "מעבד", "Memory": "זיכרון", "Storage": "אחסון", "Image": "תמונה", "IP Address": "כתובת IP",
    "Save Changes": "שמור שינויים", "Health": "בריאות", "Online": "מחובר", "Offline": "מנותק",
    "Maintenance": "תחזוקה", "Active": "פעיל", "Inactive": "לא פעיל", "Running": "רץ",
    "Stopped": "מופסק", "Up": "למעלה", "Down": "למטה", "vCPU": "vCPU", "Add VM": "הוסף מכונה וירטואלית",
    "Add Node": "הוסף צומת", "Add Container": "הוסף קונטיינר", "Add Jail": "הוסף Jail",
    "UTILIZED": "בשימוש", "GB": "GB", "TB": "TB", "Error": "שגיאה", "Success": "הצלחה", "Warning": "אזהרה"
  },
  tr: {
    "Save": "Kaydet", "Cancel": "İptal", "Loading...": "Yükleniyor...", "Actions": "İşlemler", "Search": "Ara",
    "Status": "Durum", "Name": "İsim", "Type": "Tip", "Information": "Bilgi", "Host": "Host",
    "Settings": "Ayarlar", "Logout": "Çıkış Yap", "Dashboard": "Panel", "VMs": "VM'ler",
    "Containers": "Konteynerler", "Jails": "Jails", "Network Map": "Ağ Haritası", "Cluster": "Küme",
    "Users": "Kullanıcılar", "Logs": "Günlükler", "License": "Lisans", "Role": "Rol", "Username": "Kullanıcı Adı",
    "Password": "Şifre", "Language": "Dil", "Close": "Kapat", "Edit": "Düzenle", "Delete": "Sil",
    "Apply": "Uygula", "Confirm": "Onayla", "Server": "Sunucu", "Admin": "Yönetici", "Operator": "Operatör",
    "Viewer": "İzleyici", "Unknown": "Bilinmeyen", "Host System": "Ana Sistem", "System": "Sistem",
    "CPU": "İşlemci", "Memory": "Bellek", "Storage": "Depolama", "Image": "İmaj", "IP Address": "IP Adresi",
    "Save Changes": "Değişiklikleri Kaydet", "Health": "Sağlık", "Online": "Çevrimiçi", "Offline": "Çevrimdışı",
    "Maintenance": "Bakım", "Active": "Aktif", "Inactive": "Pasif", "Running": "Çalışıyor",
    "Stopped": "Durduruldu", "Up": "Açık", "Down": "Kapalı", "vCPU": "vCPU", "Add VM": "VM Ekle",
    "Add Node": "Düğüm Ekle", "Add Container": "Konteyner Ekle", "Add Jail": "Jail Ekle",
    "UTILIZED": "KULLANILAN", "GB": "GB", "TB": "TB", "Error": "Hata", "Success": "Başarılı", "Warning": "Uyarı"
  },
  bg: {
    "Save": "Запази", "Cancel": "Отказ", "Loading...": "Зареждане...", "Actions": "Действия", "Search": "Търсене",
    "Status": "Статус", "Name": "Име", "Type": "Тип", "Information": "Информация", "Host": "Хост",
    "Settings": "Настройки", "Logout": "Изход", "Dashboard": "Табло", "VMs": "ВМ",
    "Containers": "Контейнери", "Jails": "Jails", "Network Map": "Мрежова карта", "Cluster": "Клъстер",
    "Users": "Потребители", "Logs": "Логове", "License": "Лиценз", "Role": "Роля", "Username": "Потребител",
    "Password": "Парола", "Language": "Език", "Close": "Затвори", "Edit": "Редактирай", "Delete": "Изтрий",
    "Apply": "Приложи", "Confirm": "Потвърди", "Server": "Сървър", "Admin": "Админ", "Operator": "Оператор",
    "Viewer": "Зрител", "Unknown": "Неизвестно", "Host System": "Хост система", "System": "Система",
    "CPU": "ЦП", "Memory": "Памет", "Storage": "Съхранение", "Image": "Изображение", "IP Address": "IP адрес",
    "Save Changes": "Запази промените", "Health": "Здраве", "Online": "Онлайн", "Offline": "Офлайн",
    "Maintenance": "Поддръжка", "Active": "Активен", "Inactive": "Неактивен", "Running": "Работи",
    "Stopped": "Спряно", "Up": "Нагоре", "Down": "Надолу", "vCPU": "vCPU", "Add VM": "Добави ВМ",
    "Add Node": "Добави възел", "Add Container": "Добави контейнер", "Add Jail": "Добави Jail",
    "UTILIZED": "ИЗПОЛЗВАНО", "GB": "GB", "TB": "TB", "Error": "Грешка", "Success": "Успех", "Warning": "Предупреждение"
  },
  pl: {
    "Save": "Zapisz", "Cancel": "Anuluj", "Loading...": "Ładowanie...", "Actions": "Akcje", "Search": "Szukaj",
    "Status": "Status", "Name": "Nazwa", "Type": "Typ", "Information": "Informacja", "Host": "Host",
    "Settings": "Ustawienia", "Logout": "Wyloguj", "Dashboard": "Panel", "VMs": "Maszyny wirtualne",
    "Containers": "Kontenery", "Jails": "Jails", "Network Map": "Mapa sieci", "Cluster": "Klaster",
    "Users": "Użytkownicy", "Logs": "Logi", "License": "Licencja", "Role": "Rola", "Username": "Użytkownik",
    "Password": "Hasło", "Language": "Język", "Close": "Zamknij", "Edit": "Edytuj", "Delete": "Usuń",
    "Apply": "Zastosuj", "Confirm": "Potwierdź", "Server": "Serwer", "Admin": "Admin", "Operator": "Operator",
    "Viewer": "Widz", "Unknown": "Nieznany", "Host System": "System hosta", "System": "System",
    "CPU": "CPU", "Memory": "Pamięć", "Storage": "Pamięć masowa", "Image": "Obraz", "IP Address": "Adres IP",
    "Save Changes": "Zapisz zmiany", "Health": "Stan", "Online": "Online", "Offline": "Offline",
    "Maintenance": "Konserwacja", "Active": "Aktywny", "Inactive": "Nieaktywny", "Running": "Uruchomiony",
    "Stopped": "Zatrzymany", "Up": "W górę", "Down": "W dół", "vCPU": "vCPU", "Add VM": "Dodaj VM",
    "Add Node": "Dodaj węzeł", "Add Container": "Dodaj kontener", "Add Jail": "Dodaj Jail",
    "UTILIZED": "WYKORZYSTANE", "GB": "GB", "TB": "TB", "Error": "Błąd", "Success": "Sukces", "Warning": "Ostrzeżenie"
  },
  da: {
    "Save": "Gem", "Cancel": "Annuller", "Loading...": "Indlæser...", "Actions": "Handlinger", "Search": "Søg",
    "Status": "Status", "Name": "Navn", "Type": "Type", "Information": "Information", "Host": "Vært",
    "Settings": "Indstillinger", "Logout": "Log ud", "Dashboard": "Oversigt", "VMs": "VM'er",
    "Containers": "Containere", "Jails": "Jails", "Network Map": "Netværkskort", "Cluster": "Klynge",
    "Users": "Brugere", "Logs": "Logfiler", "License": "Licens", "Role": "Rolle", "Username": "Brugernavn",
    "Password": "Adgangskode", "Language": "Sprog", "Close": "Luk", "Edit": "Rediger", "Delete": "Slet",
    "Apply": "Anvend", "Confirm": "Bekræft", "Server": "Server", "Admin": "Admin", "Operator": "Operatør",
    "Viewer": "Seer", "Unknown": "Ukendt", "Host System": "Værtssystem", "System": "System",
    "CPU": "CPU", "Memory": "Hukommelse", "Storage": "Lager", "Image": "Billede", "IP Address": "IP-adresse",
    "Save Changes": "Gem ændringer", "Health": "Helbred", "Online": "Online", "Offline": "Offline",
    "Maintenance": "Vedligeholdelse", "Active": "Aktiv", "Inactive": "Inaktiv", "Running": "Kører",
    "Stopped": "Stoppet", "Up": "Opppe", "Down": "Nede", "vCPU": "vCPU", "Add VM": "Tilføj VM",
    "Add Node": "Tilføj node", "Add Container": "Tilføj container", "Add Jail": "Tilføj Jail",
    "UTILIZED": "UDNYTTET", "GB": "GB", "TB": "TB", "Error": "Fejl", "Success": "Succes", "Warning": "Advarsel"
  },
  fi: {
    "Save": "Tallenna", "Cancel": "Peruuta", "Loading...": "Ladataan...", "Actions": "Toiminnot", "Search": "Hae",
    "Status": "Tila", "Name": "Nimi", "Type": "Tyyppi", "Information": "Tiedot", "Host": "Isäntä",
    "Settings": "Asetukset", "Logout": "Kirjaudu ulos", "Dashboard": "Ohjauspaneeli", "VMs": "VM:t",
    "Containers": "Säiliöt", "Jails": "Jails", "Network Map": "Verkkokartta", "Cluster": "Klusteri",
    "Users": "Käyttäjät", "Logs": "Lokit", "License": "Lisenssi", "Role": "Rooli", "Username": "Käyttäjätunnus",
    "Password": "Salasana", "Language": "Kieli", "Close": "Sulje", "Edit": "Muokkaa", "Delete": "Poista",
    "Apply": "Käytä", "Confirm": "Vahvista", "Server": "Palvelin", "Admin": "Ylläpitäjä", "Operator": "Operaattori",
    "Viewer": "Katsoja", "Unknown": "Tuntematon", "Host System": "Isäntäjärjestelmä", "System": "Järjestelmä",
    "CPU": "CPU", "Memory": "Muisti", "Storage": "Tallennustila", "Image": "Kuva", "IP Address": "IP-osoite",
    "Save Changes": "Tallenna muutokset", "Health": "Terveys", "Online": "Online", "Offline": "Offline",
    "Maintenance": "Huolto", "Active": "Aktiivinen", "Inactive": "Passiivinen", "Running": "Käynnissä",
    "Stopped": "Pysäytetty", "Up": "Ylhäällä", "Down": "Alhaalla", "vCPU": "vCPU", "Add VM": "Lisää VM",
    "Add Node": "Lisää solmu", "Add Container": "Lisää säiliö", "Add Jail": "Lisää Jail",
    "UTILIZED": "KÄYTÖSSÄ", "GB": "GB", "TB": "TB", "Error": "Virhe", "Success": "Onnistui", "Warning": "Varoitus"
  },
  no: {
    "Save": "Lagre", "Cancel": "Avbryt", "Loading...": "Laster...", "Actions": "Handlinger", "Search": "Søk",
    "Status": "Status", "Name": "Navn", "Type": "Type", "Information": "Informasjon", "Host": "Vert",
    "Settings": "Innstillinger", "Logout": "Logg ut", "Dashboard": "Oversikt", "VMs": "VM-er",
    "Containers": "Containere", "Jails": "Jails", "Network Map": "Nettverkskart", "Cluster": "Klynge",
    "Users": "Brukere", "Logs": "Logger", "License": "Lisens", "Role": "Rolle", "Username": "Brukernavn",
    "Password": "Passord", "Language": "Språk", "Close": "Lukk", "Edit": "Rediger", "Delete": "Slett",
    "Apply": "Bruk", "Confirm": "Bekreft", "Server": "Server", "Admin": "Admin", "Operator": "Operatør",
    "Viewer": "Seer", "Unknown": "Ukjent", "Host System": "Vertssystem", "System": "System",
    "CPU": "CPU", "Memory": "Minne", "Storage": "Lagring", "Image": "Bilde", "IP Address": "IP-adresse",
    "Save Changes": "Lagre endringer", "Health": "Helse", "Online": "Online", "Offline": "Offline",
    "Maintenance": "Vedlikehold", "Active": "Aktiv", "Inactive": "Inaktiv", "Running": "Kjører",
    "Stopped": "Stoppet", "Up": "Opp", "Down": "Ned", "vCPU": "vCPU", "Add VM": "Legg til VM",
    "Add Node": "Legg til node", "Add Container": "Legg til container", "Add Jail": "Legg til Jail",
    "UTILIZED": "UTNYTTET", "GB": "GB", "TB": "TB", "Error": "Feil", "Success": "Suksess", "Warning": "Advarsel"
  },
  hu: {
    "Save": "Mentés", "Cancel": "Mégse", "Loading...": "Betöltés...", "Actions": "Műveletek", "Search": "Keresés",
    "Status": "Állapot", "Name": "Név", "Type": "Típus", "Information": "Információ", "Host": "Gép",
    "Settings": "Beállítások", "Logout": "Kijelentkezés", "Dashboard": "Irányítópult", "VMs": "VM-ek",
    "Containers": "Konténerek", "Jails": "Jails", "Network Map": "Hálózati térkép", "Cluster": "Fürt",
    "Users": "Felhasználók", "Logs": "Naplók", "License": "Licenc", "Role": "Szerepkör", "Username": "Felhasználónév",
    "Password": "Jelszó", "Language": "Nyelv", "Close": "Bezárás", "Edit": "Szerkesztés", "Delete": "Törlés",
    "Apply": "Alkalmaz", "Confirm": "Megerősítés", "Server": "Szerver", "Admin": "Admin", "Operator": "Operátor",
    "Viewer": "Megtekintő", "Unknown": "Ismeretlen", "Host System": "Gazdarendszer", "System": "Rendszer",
    "CPU": "CPU", "Memory": "Memória", "Storage": "Tárhely", "Image": "Kép", "IP Address": "IP-cím",
    "Save Changes": "Módosítások mentése", "Health": "Állapot", "Online": "Online", "Offline": "Offline",
    "Maintenance": "Karbantartás", "Active": "Aktív", "Inactive": "Inaktív", "Running": "Fut",
    "Stopped": "Leállítva", "Up": "Fent", "Down": "Lent", "vCPU": "vCPU", "Add VM": "VM hozzáadása",
    "Add Node": "Csomópont hozzáadása", "Add Container": "Konténer hozzáadása", "Add Jail": "Jail hozzáadása",
    "UTILIZED": "KIHASZNÁLT", "GB": "GB", "TB": "TB", "Error": "Hiba", "Success": "Siker", "Warning": "Figyelmeztetés"
  },
  ro: {
    "Save": "Salvează", "Cancel": "Anulează", "Loading...": "Se încarcă...", "Actions": "Acțiuni", "Search": "Caută",
    "Status": "Stare", "Name": "Nume", "Type": "Tip", "Information": "Informații", "Host": "Gazdă",
    "Settings": "Setări", "Logout": "Deconectare", "Dashboard": "Tablou de bord", "VMs": "VM-uri",
    "Containers": "Containere", "Jails": "Jails", "Network Map": "Hartă rețea", "Cluster": "Cluster",
    "Users": "Utilizatori", "Logs": "Jurnale", "License": "Licență", "Role": "Rol", "Username": "Utilizator",
    "Password": "Parolă", "Language": "Limbă", "Close": "Închide", "Edit": "Editează", "Delete": "Șterge",
    "Apply": "Aplică", "Confirm": "Confirmă", "Server": "Server", "Admin": "Admin", "Operator": "Operator",
    "Viewer": "Vizualizator", "Unknown": "Necunoscut", "Host System": "Sistem gazdă", "System": "Sistem",
    "CPU": "CPU", "Memory": "Memorie", "Storage": "Stocare", "Image": "Imagine", "IP Address": "Adresă IP",
    "Save Changes": "Salvează modificările", "Health": "Sănătate", "Online": "Online", "Offline": "Offline",
    "Maintenance": "Mentenanță", "Active": "Activ", "Inactive": "Inactiv", "Running": "Rulează",
    "Stopped": "Oprit", "Up": "Sus", "Down": "Jos", "vCPU": "vCPU", "Add VM": "Adaugă VM",
    "Add Node": "Adaugă nod", "Add Container": "Adaugă container", "Add Jail": "Adaugă Jail",
    "UTILIZED": "UTILIZAT", "GB": "GB", "TB": "TB", "Error": "Eroare", "Success": "Succes", "Warning": "Avertisment"
  },
  uk: {
    "Save": "Зберегти", "Cancel": "Скасувати", "Loading...": "Завантаження...", "Actions": "Дії", "Search": "Пошук",
    "Status": "Статус", "Name": "Ім'я", "Type": "Тип", "Information": "Інформація", "Host": "Хост",
    "Settings": "Налаштування", "Logout": "Вийти", "Dashboard": "Панель", "VMs": "ВМ",
    "Containers": "Контейнери", "Jails": "Jails", "Network Map": "Карта мережі", "Cluster": "Кластер",
    "Users": "Користувачі", "Logs": "Логи", "License": "Ліцензія", "Role": "Роль", "Username": "Ім'я користувача",
    "Password": "Пароль", "Language": "Мова", "Close": "Закрити", "Edit": "Редагувати", "Delete": "Видалити",
    "Apply": "Застосувати", "Confirm": "Підтвердити", "Server": "Сервер", "Admin": "Адмін", "Operator": "Оператор",
    "Viewer": "Глядач", "Unknown": "Невідомо", "Host System": "Хост-система", "System": "Система",
    "CPU": "ЦП", "Memory": "Пам'ять", "Storage": "Сховище", "Image": "Образ", "IP Address": "IP-адреса",
    "Save Changes": "Зберегти зміни", "Health": "Стан", "Online": "В мережі", "Offline": "Поза мережею",
    "Maintenance": "Обслуговування", "Active": "Активний", "Inactive": "Неактивний", "Running": "Запущено",
    "Stopped": "Зупинено", "Up": "Вгору", "Down": "Вниз", "vCPU": "vCPU", "Add VM": "Додати ВМ",
    "Add Node": "Додати вузол", "Add Container": "Додати контейнер", "Add Jail": "Добавить Jail",
    "UTILIZED": "ВИКОРИСТОВУЄТЬСЯ", "GB": "ГБ", "TB": "ТБ", "Error": "Помилка", "Success": "Успіх", "Warning": "Попередження"
  },
  el: {
    "Save": "Αποθήκευση", "Cancel": "Ακύρωση", "Loading...": "Φόρτωση...", "Actions": "Ενέργειες", "Search": "Αναζήτηση",
    "Status": "Κατάσταση", "Name": "Όνομα", "Type": "Τύπος", "Information": "Πληροφορίες", "Host": "Διακομιστής",
    "Settings": "Ρυθμίσεις", "Logout": "Αποσύνδεση", "Dashboard": "Ταμπλό", "VMs": "VMs",
    "Containers": "Containers", "Jails": "Jails", "Network Map": "Χάρτης Δικτύου", "Cluster": "Cluster",
    "Users": "Χρήστες", "Logs": "Αρχεία καταγραφής", "License": "Άδεια", "Role": "Ρόλος", "Username": "Όνομα χρήστη",
    "Password": "Κωδικός πρόσβασης", "Language": "Γλώσσα", "Close": "Κλείσιμο", "Edit": "Επεξεργασία", "Delete": "Διαγραφή",
    "Apply": "Εφαρμογή", "Confirm": "Επιβεβαίωση", "Server": "Διακομιστής", "Admin": "Διαχειριστής", "Operator": "Χειριστής",
    "Viewer": "Θεατής", "Unknown": "Άγνωστο", "Host System": "Σύστημα Φιλοξενίας", "System": "Σύστημα",
    "CPU": "CPU", "Memory": "Μνήμη", "Storage": "Αποθήκευση", "Image": "Εικόνα", "IP Address": "Διεύθυνση IP",
    "Save Changes": "Αποθήκευση αλλαγών", "Health": "Υγεία", "Online": "Σε σύνδεση", "Offline": "Εκτός σύνδεσης",
    "Maintenance": "Συντήρηση", "Active": "Ενεργό", "Inactive": "Ανενεργό", "Running": "Σε εκτέλεση",
    "Stopped": "Σταματημένο", "Up": "Πάνω", "Down": "Κάτω", "vCPU": "vCPU", "Add VM": "Προσθήκη VM",
    "Add Node": "Προσθήκη κόμβου", "Add Container": "Προσθήκη container", "Add Jail": "Προσθήκη Jail",
    "UTILIZED": "ΧΡΗΣΙΜΟΠΟΙΗΜΕΝΟ", "GB": "GB", "TB": "TB", "Error": "Σφάλμα", "Success": "Επιτυχία", "Warning": "Προειδοποίηση"
  },
  ca: {
    "Save": "Desar", "Cancel": "Cancel·lar", "Loading...": "Carregant...", "Actions": "Accions", "Search": "Cercar",
    "Status": "Estat", "Name": "Nom", "Type": "Tipus", "Information": "Informació", "Host": "Amfitrió",
    "Settings": "Ajustos", "Logout": "Tancar sessió", "Dashboard": "Taulell", "VMs": "VMs",
    "Containers": "Contenidors", "Jails": "Jails", "Network Map": "Mapa de xarxa", "Cluster": "Clúster",
    "Users": "Usuaris", "Logs": "Registres", "License": "Llicència", "Role": "Rol", "Username": "Usuari",
    "Password": "Contrasenya", "Language": "Idioma", "Close": "Tancar", "Edit": "Editar", "Delete": "Eliminar",
    "Apply": "Aplicar", "Confirm": "Confirmar", "Server": "Servidor", "Admin": "Admin", "Operator": "Operador",
    "Viewer": "Visor", "Unknown": "Desconegut", "Host System": "Sistema amfitrió", "System": "Sistema",
    "CPU": "CPU", "Memory": "Memòria", "Storage": "Emmagatzematge", "Image": "Imatge", "IP Address": "Adreça IP",
    "Save Changes": "Desar canvis", "Health": "Salut", "Online": "En línia", "Offline": "Fora de línia",
    "Maintenance": "Manteniment", "Active": "Actiu", "Inactive": "Inactiu", "Running": "En execució",
    "Stopped": "Aturat", "Up": "Amunt", "Down": "Avall", "vCPU": "vCPU", "Add VM": "Afegir MV",
    "Add Node": "Afegir node", "Add Container": "Afegir contenidor", "Add Jail": "Afegir Jail",
    "UTILIZED": "UTILITZAT", "GB": "GB", "TB": "TB", "Error": "Error", "Success": "Èxit", "Warning": "Avís"
  },
  eo: {
    "Save": "Konservi", "Cancel": "Nuligi", "Loading...": "Ŝargado...", "Actions": "Agoj", "Search": "Serĉi",
    "Status": "Stato", "Name": "Nomo", "Type": "Tipo", "Information": "Informo", "Host": "Gastiganto",
    "Settings": "Agordoj", "Logout": "Elsaluti", "Dashboard": "Statpanelo", "VMs": "VM-oj",
    "Containers": "Ujoj", "Jails": "Jails", "Network Map": "Retmapo", "Cluster": "Areto",
    "Users": "Uzantoj", "Logs": "Protokoloj", "License": "Permesilo", "Role": "Rolo", "Username": "Uzantnomo",
    "Password": "Pasvorto", "Language": "Lingvo", "Close": "Fermi", "Edit": "Redakti", "Delete": "Forigi",
    "Apply": "Apliki", "Confirm": "Konfirmi", "Server": "Servilo", "Admin": "Admin", "Operator": "Operaciisto",
    "Viewer": "Spektanto", "Unknown": "Nekonata", "Host System": "Gastiga sistemo", "System": "Sistemo",
    "CPU": "ĉefprocesoro", "Memory": "Memoro", "Storage": "Stokado", "Image": "Bildo", "IP Address": "IP-adreso",
    "Save Changes": "Konservi ŝanĝojn", "Health": "Sano", "Online": "Enrete", "Offline": "Eksterrete",
    "Maintenance": "Prizorgado", "Active": "Aktiva", "Inactive": "Neaktiva", "Running": "Rulanta",
    "Stopped": "Haltigita", "Up": "Supren", "Down": "Malsupren", "vCPU": "vCPU", "Add VM": "Aldoni VM",
    "Add Node": "Aldoni nodon", "Add Container": "Aldoni ujon", "Add Jail": "Aldoni Jail",
    "UTILIZED": "UZATA", "GB": "GB", "TB": "TB", "Error": "Eroro", "Success": "Sukceso", "Warning": "Averto"
  },
  hr: {
    "Save": "Spremi", "Cancel": "Odustani", "Loading...": "Učitavanje...", "Actions": "Radnje", "Search": "Traži",
    "Status": "Status", "Name": "Ime", "Type": "Tip", "Information": "Informacije", "Host": "Poslužitelj",
    "Settings": "Postavke", "Logout": "Odjava", "Dashboard": "Nadzorna ploča", "VMs": "VM",
    "Containers": "Kontejneri", "Jails": "Jails", "Network Map": "Mrežna karta", "Cluster": "Klaster",
    "Users": "Korisnici", "Logs": "Zapisi", "License": "Licenca", "Role": "Uloga", "Username": "Korisničko ime",
    "Password": "Lozinka", "Language": "Jezik", "Close": "Zatvori", "Edit": "Uredi", "Delete": "Obriši",
    "Apply": "Primijeni", "Confirm": "Potvrdi", "Server": "Poslužitelj", "Admin": "Admin", "Operator": "Operator",
    "Viewer": "Preglednik", "Unknown": "Nepoznato", "Host System": "Host sustav", "System": "Sustav",
    "CPU": "CPU", "Memory": "Memorija", "Storage": "Pohrana", "Image": "Slika", "IP Address": "IP adresa",
    "Save Changes": "Spremi promjene", "Health": "Zdravlje", "Online": "Mrežno", "Offline": "Izvanmrežno",
    "Maintenance": "Održavanje", "Active": "Aktivno", "Inactive": "Neaktivno", "Running": "Radi",
    "Stopped": "Zaustavljeno", "Up": "Gore", "Down": "Dolje", "vCPU": "vCPU", "Add VM": "Dodaj VM",
    "Add Node": "Dodaj čvor", "Add Container": "Dodaj kontejner", "Add Jail": "Dodaj Jail",
    "UTILIZED": "ISKORIŠTENO", "GB": "GB", "TB": "TB", "Error": "Pogreška", "Success": "Uspjeh", "Warning": "Upozorenje"
  },
  sk: {
    "Save": "Uložiť", "Cancel": "Zrušiť", "Loading...": "Načítava sa...", "Actions": "Akcie", "Search": "Hľadať",
    "Status": "Stav", "Name": "Meno", "Type": "Typ", "Information": "Informácie", "Host": "Hostiteľ",
    "Settings": "Nastavenia", "Logout": "Odhlásiť sa", "Dashboard": "Nástenka", "VMs": "VM",
    "Containers": "Kontajnery", "Jails": "Jails", "Network Map": "Mapa siete", "Cluster": "Cluster",
    "Users": "Používatelia", "Logs": "Záznamy", "License": "Licencia", "Role": "Rola", "Username": "Používateľské meno",
    "Password": "Heslo", "Language": "Jazyk", "Close": "Zavrieť", "Edit": "Upraviť", "Delete": "Zmazať",
    "Apply": "Použiť", "Confirm": "Potvrdiť", "Server": "Server", "Admin": "Administrátor", "Operator": "Operátor",
    "Viewer": "Prehliadač", "Unknown": "Neznámy", "Host System": "Hostiteľský systém", "System": "Systém",
    "CPU": "CPU", "Memory": "Pamäť", "Storage": "Úložisko", "Image": "Obraz", "IP Address": "IP adresa",
    "Save Changes": "Uložiť zmeny", "Health": "Zdravie", "Online": "Online", "Offline": "Offline",
    "Maintenance": "Údržba", "Active": "Aktívny", "Inactive": "Neaktívny", "Running": "Beží",
    "Stopped": "Zastavené", "Up": "Hore", "Down": "Dole", "vCPU": "vCPU", "Add VM": "Pridať VM",
    "Add Node": "Pridať uzol", "Add Container": "Pridať kontajner", "Add Jail": "Pridať Jail",
    "UTILIZED": "VYUŽITÉ", "GB": "GB", "TB": "TB", "Error": "Chyba", "Success": "Úspech", "Warning": "Varovanie"
  },
  sl: {
    "Save": "Shrani", "Cancel": "Prekliči", "Loading...": "Nalaganje...", "Actions": "Dejanja", "Search": "Išči",
    "Status": "Status", "Name": "Ime", "Type": "Vrsta", "Information": "Informacije", "Host": "Gostitelj",
    "Settings": "Nastavitve", "Logout": "Odjava", "Dashboard": "Nadzorna plošča", "VMs": "VM",
    "Containers": "Zabojniki", "Jails": "Jails", "Network Map": "Zemljevid omrežja", "Cluster": "Gruča",
    "Users": "Uporabniki", "Logs": "Dnevniki", "License": "Licenca", "Role": "Vloga", "Username": "Uporabniško ime",
    "Password": "Geslo", "Language": "Jezik", "Close": "Zapri", "Edit": "Uredi", "Delete": "Izbriši",
    "Apply": "Uporabi", "Confirm": "Potrdi", "Server": "Strežnik", "Admin": "Admin", "Operator": "Operater",
    "Viewer": "Gledalec", "Unknown": "Neznano", "Host System": "Gostiteljski sistem", "System": "Sistem",
    "CPU": "CPE", "Memory": "Pomnilnik", "Storage": "Shramba", "Image": "Slika", "IP Address": "IP naslov",
    "Save Changes": "Shrani spremembe", "Health": "Zdravje", "Online": "Na spletu", "Offline": "Brez povezave",
    "Maintenance": "Vzdrževanje", "Active": "Aktiven", "Inactive": "Neaktiven", "Running": "Dela",
    "Stopped": "Ustavljeno", "Up": "Gor", "Down": "Dol", "vCPU": "vCPU", "Add VM": "Dodaj VM",
    "Add Node": "Dodaj vozlišče", "Add Container": "Dodaj zabojnik", "Add Jail": "Dodaj Jail",
    "UTILIZED": "UPORABLJENO", "GB": "GB", "TB": "TB", "Error": "Napaka", "Success": "Uspeh", "Warning": "Opozorilo"
  },
  sr: {
    "Save": "Sačuvaj", "Cancel": "Otkaži", "Loading...": "Učitavanje...", "Actions": "Akcije", "Search": "Pretraga",
    "Status": "Status", "Name": "Ime", "Type": "Tip", "Information": "Informacije", "Host": "Host",
    "Settings": "Podešavanja", "Logout": "Odjava", "Dashboard": "Kontrolna tabla", "VMs": "VM",
    "Containers": "Kontejneri", "Jails": "Jails", "Network Map": "Mrežna mapa", "Cluster": "Klaster",
    "Users": "Korisnici", "Logs": "Zapisi", "License": "Licenca", "Role": "Uloga", "Username": "Korisničko ime",
    "Password": "Lozinka", "Language": "Jezik", "Close": "Zatvori", "Edit": "Uredi", "Delete": "Obriši",
    "Apply": "Primeni", "Confirm": "Potvrdi", "Server": "Server", "Admin": "Admin", "Operator": "Operator",
    "Viewer": "Pregledač", "Unknown": "Nepoznato", "Host System": "Host sistem", "System": "Sistem",
    "CPU": "CPU", "Memory": "Memorija", "Storage": "Skladište", "Image": "Slika", "IP Address": "IP adresa",
    "Save Changes": "Sačuvaj promene", "Health": "Zdravlje", "Online": "Na mreži", "Offline": "Vann mreže",
    "Maintenance": "Održavanje", "Active": "Aktivno", "Inactive": "Neaktivno", "Running": "Radi",
    "Stopped": "Zaustavljeno", "Up": "Gore", "Down": "Dole", "vCPU": "vCPU", "Add VM": "Dodaj VM",
    "Add Node": "Dodaj čvor", "Add Container": "Dodaj kontejner", "Add Jail": "Dodaj Jail",
    "UTILIZED": "ISKORIŠĆENO", "GB": "GB", "TB": "TB", "Error": "Greška", "Success": "Uspeh", "Warning": "Upozorenje"
  },
  et: {
    "Save": "Salvesta", "Cancel": "Tühista", "Loading...": "Laadimine...", "Actions": "Tegevused", "Search": "Otsi",
    "Status": "Staatus", "Name": "Nimi", "Type": "Tüüp", "Information": "Info", "Host": "Host",
    "Settings": "Seaded", "Logout": "Logi välja", "Dashboard": "Töölaud", "VMs": "VM-id",
    "Containers": "Konteinerid", "Jails": "Jails", "Network Map": "Võrgukaart", "Cluster": "Klaster",
    "Users": "Kasutajad", "Logs": "Logid", "License": "Litsents", "Role": "Roll", "Username": "Kasutajanimi",
    "Password": "Parool", "Language": "Keel", "Close": "Sulge", "Edit": "Muuda", "Delete": "Kustuta",
    "Apply": "Rakenda", "Confirm": "Kinnita", "Server": "Server", "Admin": "Admin", "Operator": "Operaator",
    "Viewer": "Vaataja", "Unknown": "Tundmatu", "Host System": "Hostisüsteem", "System": "Süsteem",
    "CPU": "CPU", "Memory": "Mälu", "Storage": "Salvestusruum", "Image": "Kujutis", "IP Address": "IP-aadress",
    "Save Changes": "Salvesta muudatused", "Health": "Tervis", "Online": "Online", "Offline": "Offline",
    "Maintenance": "Hooldus", "Active": "Aktiivne", "Inactive": "Inaktiivne", "Running": "Töötab",
    "Stopped": "Peatatud", "Up": "Üles", "Down": "Alla", "vCPU": "vCPU", "Add VM": "Lisa VM",
    "Add Node": "Lisa sõlm", "Add Container": "Lisa konteiner", "Add Jail": "Lisa Jail",
    "UTILIZED": "KASUTATUD", "GB": "GB", "TB": "TB", "Error": "Viga", "Success": "Edukas", "Warning": "Hoiatus"
  },
  lv: {
    "Save": "Saglabāt", "Cancel": "Atcelt", "Loading...": "Ielādē...", "Actions": "Darbības", "Search": "Meklēt",
    "Status": "Statuss", "Name": "Vārds", "Type": "Tips", "Information": "Informācija", "Host": "Hosts",
    "Settings": "Iestatījumi", "Logout": "Iziet", "Dashboard": "Informācijas panelis", "VMs": "VM",
    "Containers": "Konteineri", "Jails": "Jails", "Network Map": "Tīkla karte", "Cluster": "Klasteris",
    "Users": "Lietotāji", "Logs": "Žurnāli", "License": "Licence", "Role": "Loma", "Username": "Lietotājvārds",
    "Password": "Parole", "Language": "Valoda", "Close": "Aizvērt", "Edit": "Rediģēt", "Delete": "Dzēst",
    "Apply": "Lietot", "Confirm": "Apstiprināt", "Server": "Serveris", "Admin": "Admins", "Operator": "Operators",
    "Viewer": "Skatītājs", "Unknown": "Nezināms", "Host System": "Hosta sistēma", "System": "Sistēma",
    "CPU": "CPU", "Memory": "Atmiņa", "Storage": "Krātuve", "Image": "Attēls", "IP Address": "IP adrese",
    "Save Changes": "Saglabāt izmaiņas", "Health": "Veselība", "Online": "Tiešsaistē", "Offline": "Bezsaistē",
    "Maintenance": "Apkope", "Active": "Aktīvs", "Inactive": "Neaktīvs", "Running": "Darbojas",
    "Stopped": "Apturēts", "Up": "Augšā", "Down": "Lejā", "vCPU": "vCPU", "Add VM": "Pievienot VM",
    "Add Node": "Pievienot mezglu", "Add Container": "Pievienot konteineru", "Add Jail": "Pievienot Jail",
    "UTILIZED": "IZMANTOTS", "GB": "GB", "TB": "TB", "Error": "Kļūda", "Success": "Veiksmīgi", "Warning": "Brīdinājums"
  },
  lt: {
    "Save": "Išsaugoti", "Cancel": "Atšaukti", "Loading...": "Kraunama...", "Actions": "Veiksmai", "Search": "Paieška",
    "Status": "Būsena", "Name": "Vardas", "Type": "Tipas", "Information": "Informacija", "Host": "Serveris",
    "Settings": "Nustatymai", "Logout": "Atsijungti", "Dashboard": "Skydelis", "VMs": "VM",
    "Containers": "Konteineriai", "Jails": "Jails", "Network Map": "Tinklo žemėlapis", "Cluster": "Klasteris",
    "Users": "Vartotojai", "Logs": "Žurnalai", "License": "Licencija", "Role": "Rolė", "Username": "Vartotojo vardas",
    "Password": "Slaptažodis", "Language": "Kalba", "Close": "Uždaryti", "Edit": "Redaguoti", "Delete": "Ištrinti",
    "Apply": "Taikyti", "Confirm": "Patvirtinti", "Server": "Serveris", "Admin": "Administratorius", "Operator": "Operatorius",
    "Viewer": "Žiūrovas", "Unknown": "Nežinoma", "Host System": "Pagrindinė sistema", "System": "Sistema",
    "CPU": "CPU", "Memory": "Atmintis", "Storage": "Saugykla", "Image": "Atvaizdas", "IP Address": "IP adresas",
    "Save Changes": "Išsaugoti pakeitimus", "Health": "Būsena", "Online": "Prisijungęs", "Offline": "Atsijungęs",
    "Maintenance": "Priežiūra", "Active": "Aktyvus", "Inactive": "Neaktyvus", "Running": "Veikia",
    "Stopped": "Sustabdytas", "Up": "Viršun", "Down": "Žemyn", "vCPU": "vCPU", "Add VM": "Pridėti VM",
    "Add Node": "Pridėti mazgą", "Add Container": "Pridėti konteinerį", "Add Jail": "Pridėti Jail",
    "UTILIZED": "PANAUDOTA", "GB": "GB", "TB": "TB", "Error": "Klaida", "Success": "Pavyko", "Warning": "Įspėjimas"
  },
  id: {
    "Save": "Simpan", "Cancel": "Batal", "Loading...": "Memuat...", "Actions": "Tindakan", "Search": "Cari",
    "Status": "Status", "Name": "Nama", "Type": "Tipe", "Information": "Informasi", "Host": "Host",
    "Settings": "Pengaturan", "Logout": "Keluar", "Dashboard": "Dasbor", "VMs": "VM",
    "Containers": "Kontainer", "Jails": "Jails", "Network Map": "Peta Jaringan", "Cluster": "Klaster",
    "Users": "Pengguna", "Logs": "Log", "License": "Lisensi", "Role": "Peran", "Username": "Nama Pengguna",
    "Password": "Kata Sandi", "Language": "Bahasa", "Close": "Tutup", "Edit": "Edit", "Delete": "Hapus",
    "Apply": "Terapkan", "Confirm": "Konfirmasi", "Server": "Server", "Admin": "Admin", "Operator": "Operator",
    "Viewer": "Pengamat", "Unknown": "Tidak Diketahui", "Host System": "Sistem Host", "System": "Sistem",
    "CPU": "CPU", "Memory": "Memori", "Storage": "Penyimpanan", "Image": "Citra", "IP Address": "Alamat IP",
    "Save Changes": "Simpan Perubahan", "Health": "Kesehatan", "Online": "Daring", "Offline": "Luring",
    "Maintenance": "Pemeliharaan", "Active": "Aktif", "Inactive": "Tidak Aktif", "Running": "Berjalan",
    "Stopped": "Berhenti", "Up": "Naik", "Down": "Turun", "vCPU": "vCPU", "Add VM": "Tambah VM",
    "Add Node": "Tambah Node", "Add Container": "Tambah Kontainer", "Add Jail": "Tambah Jail",
    "UTILIZED": "DIGUNAKAN", "GB": "GB", "TB": "TB", "Error": "Kesalahan", "Success": "Berhasil", "Warning": "Peringatan"
  },
  vi: {
    "Save": "Lưu", "Cancel": "Hủy", "Loading...": "Đang tải...", "Actions": "Hành động", "Search": "Tìm kiếm",
    "Status": "Trạng thái", "Name": "Tên", "Type": "Loại", "Information": "Thông tin", "Host": "Máy chủ",
    "Settings": "Cài đặt", "Logout": "Đăng xuất", "Dashboard": "Bảng điều khiển", "VMs": "Máy ảo",
    "Containers": "Container", "Jails": "Jails", "Network Map": "Sơ đồ mạng", "Cluster": "Cụm",
    "Users": "Người dùng", "Logs": "Nhật ký", "License": "Giấy phép", "Role": "Vai trò", "Username": "Tên đăng nhập",
    "Password": "Mật khẩu", "Language": "Ngôn ngữ", "Close": "Đóng", "Edit": "Sửa", "Delete": "Xóa",
    "Apply": "Áp dụng", "Confirm": "Xác nhận", "Server": "Máy chủ", "Admin": "Quản trị viên", "Operator": "Vận hành",
    "Viewer": "Người xem", "Unknown": "Không xác định", "Host System": "Hệ thống máy chủ", "System": "Hệ thống",
    "CPU": "CPU", "Memory": "Bộ nhớ", "Storage": "Lưu trữ", "Image": "Hình ảnh", "IP Address": "Địa chỉ IP",
    "Save Changes": "Lưu thay đổi", "Health": "Sức khỏe", "Online": "Trực tuyến", "Offline": "Ngoại tuyến",
    "Maintenance": "Bảo trì", "Active": "Hoạt động", "Inactive": "Không hoạt động", "Running": "Đang chạy",
    "Stopped": "Đã dừng", "Up": "Lên", "Down": "Xuống", "vCPU": "vCPU", "Add VM": "Thêm máy ảo",
    "Add Node": "Thêm nút", "Add Container": "Thêm container", "Add Jail": "Thêm Jail",
    "UTILIZED": "ĐÃ SỬ DỤNG", "GB": "GB", "TB": "TB", "Error": "Lỗi", "Success": "Thành công", "Warning": "Cảnh báo"
  },
  th: {
    "Save": "บันทึก", "Cancel": "ยกเลิก", "Loading...": "กำลังโหลด...", "Actions": "การดำเนินการ", "Search": "ค้นหา",
    "Status": "สถานะ", "Name": "ชื่อ", "Type": "ประเภท", "Information": "ข้อมูล", "Host": "โฮสต์",
    "Settings": "การตั้งค่า", "Logout": "ออกจากระบบ", "Dashboard": "แผงควบคุม", "VMs": "VMs",
    "Containers": "คอนเทนเนอร์", "Jails": "Jails", "Network Map": "แผนที่เครือข่าย", "Cluster": "คลัสเตอร์",
    "Users": "ผู้ใช้งาน", "Logs": "บันทึก", "License": "ใบอนุญาต", "Role": "บทบาท", "Username": "ชื่อผู้ใช้",
    "Password": "รหัสผ่าน", "Language": "ภาษา", "Close": "ปิด", "Edit": "แก้ไข", "Delete": "ลบ",
    "Apply": "นำไปใช้", "Confirm": "ยืนยัน", "Server": "เซิร์ฟเวอร์", "Admin": "ผู้ดูแลระบบ", "Operator": "ผู้ปฏิบัติการ",
    "Viewer": "ผู้เข้าชม", "Unknown": "ไม่ทราบ", "Host System": "ระบบโฮสต์", "System": "ระบบ",
    "CPU": "CPU", "Memory": "หน่วยความจำ", "Storage": "พื้นที่เก็บข้อมูล", "Image": "รูปภาพ", "IP Address": "ที่อยู่ IP",
    "Save Changes": "บันทึกการเปลี่ยนแปลง", "Health": "สุขภาพ", "Online": "ออนไลน์", "Offline": "ออฟไลน์",
    "Maintenance": "การบำรุงรักษา", "Active": "เปิดใช้งาน", "Inactive": "ปิดใช้งาน", "Running": "กำลังทำงาน",
    "Stopped": "หยุดแล้ว", "Up": "ขึ้น", "Down": "ลง", "vCPU": "vCPU", "Add VM": "เพิ่ม VM",
    "Add Node": "เพิ่มโหนด", "Add Container": "เพิ่มคอนเทนเนอร์", "Add Jail": "เพิ่ม Jail",
    "UTILIZED": "ที่ใช้ไป", "GB": "GB", "TB": "TB", "Error": "ข้อผิดพลาด", "Success": "สำเร็จ", "Warning": "คำเตือน"
  },
  zh: {
    "Browser": "浏览器",
    "Browser Info": "浏览器信息",
    "System Live": "系统实时状态",
    "Nodes Online": "在线节点",
    "Infrastructure Overview": "基础设施概览",
    "System Health": "系统健康状况",
    "Live resource utilization metrics": "实时资源利用率指标",
    "CPU Usage": "CPU 使用率",
    "Memory Usage": "内存使用率",
    "Storage Usage": "存储使用率",
    "Active Nodes": "活动节点",
    "Total VMs": "总虚拟机数",
    "Total Containers": "总容器数",
    "Total Jails": "总 Jails 数",
    "Recent Activity": "近期活动",
    "No recent activity detected": "未检测到近期活动",
    "View all activity": "查看所有活动",
    "Metrics History": "指标历史",
    "Resource Distribution": "资源分布",
    "Network Traffic": "网络流量",
    "Disk Usage": "磁盘使用情况",
    "Network In": "入站网络",
    "Network Out": "出站网络",
    "Active VMs": "活动虚拟机",
    "Stopped VMs": "已停止的虚拟机",
    "Running Containers": "运行中的容器",
    "Active Jails": "活动 Jails",
    "Uptime": "运行时间",
    "CPU Load": "CPU 负载",
    "Save": "保存",
    "Cancel": "取消",
    "Loading...": "加载中...",
    "Actions": "操作",
    "Search": "搜索",
    "Status": "状态",
    "Name": "名称",
    "Type": "类型",
    "Information": "信息",
    "Host": "主机",
    "Settings": "设置",
    "Logout": "退出登录",
    "Dashboard": "仪表盘",
    "VMs": "虚拟机",
    "Containers": "容器",
    "Jails": "Jails",
    "Network Map": "网络地图",
    "Cluster": "集群",
    "Users": "用户",
    "Logs": "日志",
    "License": "许可",
    "Role": "角色",
    "Username": "用户名",
    "Password": "密码",
    "Language": "语言",
    "Close": "关闭",
    "Edit": "编辑",
    "Delete": "删除",
    "Apply": "应用",
    "Confirm": "确认",
    "Server": "服务器",
    "Admin": "管理",
    "Operator": "操作员",
    "Viewer": "查看者",
    "Unknown": "未知",
    "Host System": "宿主系统",
    "System": "系统",
    "CPU": "CPU",
    "Memory": "内存",
    "Storage": "存储",
    "Image": "镜像",
    "IP Address": "IP 地址"
  },

};

const localesDir = path.join(process.cwd(), 'src/locales');
const localeFiles = fs.readdirSync(localesDir).filter(f => f.endsWith('.ts') && f !== 'en.ts' && f !== 'index.ts');

for (const file of localeFiles) {
  const lang = file.split('.')[0];
  const dict = dictionaries[lang] || dictionaries[lang.split('-')[0]] || {};
  
  const finalFlat = {};
  for (const key in enFlat) {
    const enVal = enFlat[key];
    if (dict[enVal]) {
      finalFlat[key] = dict[enVal];
    } else {
      const isFictional = ['atl', 'doth', 'elv', 'qav', 'qvy', 'tlh'].includes(lang);
      if (isFictional) {
          finalFlat[key] = generateThematicWord(enVal, lang);
      } else {
          finalFlat[key] = pseudoTranslate(enVal, lang);
      }
    }
  }
  
  const finalObj = { translation: unflatten(finalFlat) };
  const filePath = path.join(localesDir, file);
  const content = `const ${lang.replace('-', '_')} = ${JSON.stringify(finalObj, null, 2)};\n\nexport default ${lang.replace('-', '_')};\n`;
  fs.writeFileSync(filePath, content);
  console.log(`Updated ${file}`);
}
